### ISSUE TITLE
Models imported from Maya

### ISSUE THREAD

**Issue by Joen-UnLogick** [huika/UMA#14]
There seems to be one or more problems when creating slots from fbx files exported from maya.

Callstacks may look likt his:

ArgumentNullException: Argument cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[UnityEngine.Transform,UnityEngine.Transform].TryGetValue (UnityEngine.Transform key, UnityEngine.Transform& value) (at /Users/builduser/buildslave/monoAndRuntimeClassLibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:58
UMA.SkinnedMeshCombiner.RecursivelyMapToNewRoot (UnityEngine.Transform bone, UnityEngine.Transform hierarchyRoot, System.Collections.Generic.Dictionary`2 boneMap)
UMA.SkinnedMeshCombiner.RecursivelyMapToNewRoot (UnityEngine.Transform bone, UnityEngine.Transform hierarchyRoot, System.Collections.Generic.Dictionary`2 boneMap)
UMA.SkinnedMeshCombiner.RecursivelyMapToNewRoot (UnityEngine.Transform bone, UnityEngine.Transform hierarchyRoot, System.Collections.Generic.Dictionary`2 boneMap)
UMA.SkinnedMeshCombiner.CloneBoneListInNewHierarch y (UnityEngine.Transform rootBone, UnityEngine.Transform[] bones, System.Collections.Generic.Dictionary`2 boneMap)
UMA.SkinnedMeshCombiner.CombineMeshes (UMA.CombineInstance& target, .CombineInstance[] sources, UnityEngine.Transform rootBone, System.Collections.Generic.Dictionary`2 boneMap)
UMA.SkinnedMeshCombiner.CombineMeshes (UnityEngine.SkinnedMeshRenderer target, .CombineInstance[] sources, System.Collections.Generic.Dictionary`2 boneMap)
UMA.UMADefaultMeshCombiner.UpdateUMAMesh (Boolean updatedAtlas, UMA.UMAData umaData, System.String[] textureNameList, Int32 atlasResolution)
UMA.UMAGeneratorBuiltin.UpdateUMAMesh (Boolean updatedAtlas)
UMA.UMAGeneratorBuiltin.HandleDirtyUpdate (UMA.UMAData data)
UMA.UMAGeneratorBuiltin.OnDirtyUpdate ()
UMA.UMAGeneratorBuiltin.Update ()

I've already spent a few hours without locating the problem.

**Comment by RhodeRash** [comment]
I'm receiving this error when trying to create the slot via the MaterialBuilder with blender exported fbx.

I'm using Blender v2.73 and Unity v 4.6.3f1

![unity_console](https://cloud.githubusercontent.com/assets/11764155/6956536/b1b2e820-d8b5-11e4-99f7-7a29f437eb76.png)
![blender_fbx_export_settings](https://cloud.githubusercontent.com/assets/11764155/6956538/b7c9aa64-d8b5-11e4-8625-78154c1c6166.png)

**Comment by RhodeRash** [comment]
Some additional information.... I have been tracing the logic through the code and found that the logic was unable to find the "Hips" bone on the SkinnedMeshRender of the data parameter in the AlignBindPose method on the SkinnedMeshAligner class. I checked the skinned mesh render of my imported fbx and it appears to be selecting the Global bone as the root bone. I checked the other assets and they appear to have their root bone set to "Hips". I am now investigating if it is a problem with importing to Unity or if it is a problem with exporting from Belender. Either way the problems seems to be that it can't find the "Hips" bone. The bone is actually present in the bones of the SMR but it is below the Global bone and not a parent bone thus the existing code/logic can't find it as it always looks up to the parent and attempts to find the child bone. In this case the "Hips" bone is 2 levels down so it is never found.

![my_fbx_smr_inspector](https://cloud.githubusercontent.com/assets/11764155/6974010/a4cd7202-d954-11e4-8537-bf52d59a9164.png)
![uma_human_male_smr_inspector](https://cloud.githubusercontent.com/assets/11764155/6974011/a8525276-d954-11e4-9817-42c60990a8c6.png)
![2_levels_down_from_assigned_root_bone](https://cloud.githubusercontent.com/assets/11764155/6974013/acf02560-d954-11e4-844f-b9af0e76ff62.png)

**Comment by ecurtz** [comment]
I believe the issue with root bones above "hips" has been corrected in UMA2 via the null check in commit 59f8f98 in DeathToScriptableObjects.

**Comment by RhodeRash** [comment]
Thanks for the feedback. I did find that there is a know issue with Blender v2.73a exporting FBX version 7.4 Binary.

Blender v2.73a Settings (These settings worked for me)
![blender_settings](https://cloud.githubusercontent.com/assets/11764155/6976710/18b99862-d973-11e4-87d6-c81e3de7e6ff.png)

**Comment by huika** [comment]
The fast way to solve this is to bind the skeleton using "bind to: selected joints" and only include bones starting at Hips bone hierarchy.
This prevents Maya from including UMA_Male_Rig, Global and Position on the vertex weight group and add skin influence to those. That´s what was generating the errors I´ve received so far.
This also solves the error RhodeRash posted (https://github.com/huika/UMA/issues/14) concerning Material Builder not finding "Hips" bone on the SkinnedMeshRender.
