### ISSUE TITLE
Display of versioning, what version are we on?

### ISSUE THREAD

**Issue by MelvinLoos** [huika/UMA#22]
It is very confusing which version this repository is on, nor is it impossible to find older versions.
I came on this repository through the UMA2x wiki page but I cannot find any trace of a 2.0 version. The  last version mentioned in the readme.md (not really a great place for keeping a change log BTW) is version 1.0.1.0R which I find hard to believe since the version mentioned on the asset store is much higher. So which version is it currently and is it maybe an idea to use the git tag system for tagging releases? This is done by many repositories and also the recommended approach.

**Comment by MelvinLoos** [comment]
Also I would recommend using semver (http://semver.org) for version numbering.
But that is more a developers preference.

**Comment by Jaimi** [comment]
Added version indicator in Readme so it would display on front page.

**Comment by MelvinLoos** [comment]
Yeahhh that only fixes part of the problem... I still don't know the exact version since an x is not a version number although it finally tells me that this is version 2. The reason I started this issue is because I hoped, since this is an open source project, that the community would discuss and decide upon a versioning systematic and then would systematically keep this versioning up to date. However as I see this project is not really maintained by anyone and no one feels obliged to manage it in any way I guess this is a failed attempt.

**Comment by Jaimi** [comment]
I'm just attempting to address old issues and clean up the issue list - as for how versioning works, there does appear to be a version number generated when they do the build and update the asset store, but I'm not privy to the process as to how it gets generated. Not sure the best place to get a dialog going -- likely the Skype channel would be best.
