### ISSUE TITLE
'Convert Mip Maps' are only created when 'Convert Render Texture' is enabled.

### ISSUE THREAD

**Issue by sumitgood** [huika/UMA#27]
Problem:
'Convert Mip Maps' are only created when 'Convert Render Texture' is enabled.

Solution:

Eli Curtz said: 
destinationTexture.useMipMap = umaGenerator.convertMipMaps; 
after line 80 on TextureProcessPROCoroutine.cs

Here's a few screenshots:

Convert Render Texture off + Convert Mip Maps on  vs  pbr without uma 2:

http://i.imgur.com/RBRwFZ1.png

Convert Render Texture on + convert mip maps on 

http://i.imgur.com/b1tpn4o.png

After bug fix:

http://i.imgur.com/DMaaQWB.png

**Comment by Jaimi** [comment]
Tested, fix is working
