### ISSUE TITLE
Color32 Alpha on SetOverlayColor doesnt work

### ISSUE THREAD

**Issue by sumitgood** [huika/UMA#28]
Tried the following: 

Boots.SetOverlayColor(new Color32(0,255,0,255), "Boots");  

It doesn't matter if its 0 128 255 in the alpha channel it makes no difference, 

Any solution or bug fix?

**Comment by SecretAnorak** [comment]
This depends very much on what shader you are using. If you are using the legacy or default standard shader then it will have no effect and is expected behaviour. If you want "Ghost Boots" you will have to create them with a different UMAMaterial based on a transparent shader.

**Comment by scx0r** [comment]
Actually it was a bug with code I was told the fix by Eli

**Comment by Jaimi** [comment]
Hi Sumitgood -

What is the bug? Is it already fixed in the repository?

**Comment by virror** [comment]
Fixed!
