### ISSUE TITLE
Missing bone errors

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#29]
All vertex groups are weighted to the torso, including toe and foot, yet an error message is still received about missing bones when generating a character.
![screenhunter_605 jun 05 11 45](https://cloud.githubusercontent.com/assets/12765338/8010474/7426a91e-0b7e-11e5-8333-8e3de2a4357e.jpg)

**Comment by huika** [comment]
This is happening if you create an avatar that don´t include and slot that provides leg bones, for example if you´re testing generating an avatar only with a torso or head slot.
This error happens because the resulting skeleton won´t include all bones that mecanim requires.
