### ISSUE TITLE
Changing the Generated Character.asset name Fails to Load

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#30]
Changing the Generated Character.asset name after it is saved, causes it to not Load in Unity 5 UMA 2.0.

![screenhunter_710 jun 17 12 10](https://cloud.githubusercontent.com/assets/12765338/8212476/f7464e52-14e9-11e5-9b65-2dc341e55fcc.jpg)

**Comment by Jaimi** [comment]
Can't reproduce in Unity 5.3. Ist this still an issue?

**Comment by virror** [comment]
Cant reproduce either. Also i have a very hard time believing that the filename it self was the cause of this issue.
