### ISSUE TITLE
Converted Normals not showing properly

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#31]
Tried most option and nothing seems to fix it. The unconverted normals are fine. The Maps were made with UMA Material Builder. 

You can see how there is no normal on the abdomen area as well as pronounced seams.

![converted](https://cloud.githubusercontent.com/assets/12765338/8258135/9e6109e2-1680-11e5-877b-c2a90de649ad.png)

![unconverted n](https://cloud.githubusercontent.com/assets/12765338/8258139/a792a372-1680-11e5-8ce7-4d92e87fe7a3.png)

**Comment by Joen-UnLogick** [comment]
What shader are you using?

Looks like you're using the legacy material builder when you're not using the Legacy shader. 
The Legacy Material Builder should only be used for the legacy shader.

**Comment by justbtoo** [comment]
Thanks for the email Joen.

Everything is Default Legacy. 

Regards

Will


--------------------------------------------
On Fri, 6/19/15, Joen Joensen (UnLogick) <notifications@github.com> wrote:

 Subject: Re: [UMA] Converted Normals not showing properly (#31)
 To: "huika/UMA" <UMA@noreply.github.com>
 Cc: "justbtoo" <williambarry02@yahoo.com>
 Date: Friday, June 19, 2015, 6:00 PM
 
 What shader are you using?
 
 Looks like you're using the legacy material builder
 when you're not using the Legacy shader. 
 
 The Legacy Material Builder should only be used for the
 legacy shader.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by justbtoo** [comment]
Ok. It's working. Normal Map was just set as Normal Map instead of texture in the material builder. Thanks.

Will

--------------------------------------------
On Fri, 6/19/15, Joen Joensen (UnLogick) <notifications@github.com> wrote:

 Subject: Re: [UMA] Converted Normals not showing properly (#31)
 To: "huika/UMA" <UMA@noreply.github.com>
 Cc: "justbtoo" <williambarry02@yahoo.com>
 Date: Friday, June 19, 2015, 6:00 PM
 
 What shader are you using?
 
 Looks like you're using the legacy material builder
 when you're not using the Legacy shader. 
 
 The Legacy Material Builder should only be used for the
 legacy shader.
 
 —
 Reply to this email directly or view
 it on GitHub.
