### ISSUE TITLE
Custom inner mouth overlay doesn't save on female recipe

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#34]
Replacing the default inner mouth overlay for a custom generated female recipe doesn't save.

New Inner mouth overlay is added to a female recipe and previous is removed (not during run time).

On loading the recipe during run-time  it switches back to the default inner mouth overlay.

**Comment by Jaimi** [comment]
This is actually by design. It pulls the overlay by name from the OverlayLibrary, so if you have multiple of the same name, it will find the old one first. To get past the error, you should remove the old one from the library, or give the new one a new name.
