### ISSUE TITLE
Multiple material source meshes converted to incomplete slots

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#38]
UMA used to combine all sub meshes into a slot, but now it preserves the sub meshes with no way to assign any material to any sub mesh but the first.

![screenhunter_1416 aug 04 10 27](https://cloud.githubusercontent.com/assets/12765338/9064012/77be61f4-3a98-11e5-8746-4a55aa8a875a.jpg)

Top has 2 materials. Part of the top is missing around the arms.

![screenhunter_1417 aug 04 10 45](https://cloud.githubusercontent.com/assets/12765338/9064016/7b4f2042-3a98-11e5-8d8d-48d932f4be67.jpg)

**Comment by Joen-UnLogick** [comment]
Fixed in branch unity53, it now creates one slot per submesh. Please verify.
