### ISSUE TITLE
Root/Global position Character hovering above the ground.

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#40]
Character is hovering above the ground a few inches. Possibly the Global position

![screenhunter_1610 aug 09 11 32](https://cloud.githubusercontent.com/assets/12765338/9155591/642cd544-3e8a-11e5-990d-bf239aa1d2c6.jpg)

![screenhunter_1608 aug 09 11 23](https://cloud.githubusercontent.com/assets/12765338/9155559/dc0aed90-3e89-11e5-8dc5-1c081a45bf65.jpg)

**Comment by ecurtz** [comment]
As discussed with Will, this is from an offset in the Capsule Collider:
UMA/Content/UMA/Humanoid/Slots/AdditionalSlots/CapsuleCollider/CapsuleColliderSloScript.cs line 35

My recollection is that this offset was just copied over from the original collider code though, so I'm not sure if there might be an important reason for it to be there related to the character controller or something?

**Comment by virror** [comment]
Cant see any reason what so ever for the offset, so im removing it.
