### ISSUE TITLE
NetworkAnimator and UMA problem

### ISSUE THREAD

**Issue by dwgames** [huika/UMA#41]
in UpdateAvatar(UMAData umaData)  UMA does this:

Object.DestroyImmediate(animator);

If done with a NetworkAnimator component attached to that animator it becomes a problem.

**Comment by VictorHagsand** [comment]
This is now fixed. NetworkAnimator will be recreated but state recreation must still be handled by the user.

**Comment by Jaimi** [comment]
Closed per request
