### ISSUE TITLE
Cannot Build Slots from 3DS Max FBX Files in UMA 2

### ISSUE THREAD

**Issue by SecretAnorak** [huika/UMA#44]
Slot meshes created from FBX files generated by 3ds max have mangled vertices. 

Converted using UMA 1 then optimized for UMA 2:
![tunicbefore](https://cloud.githubusercontent.com/assets/11591231/9395114/5a740bb4-4784-11e5-9ed1-f02f1952890f.png)
Converted using UMA 2:
![tunicafter](https://cloud.githubusercontent.com/assets/11591231/9395117/5f7c5328-4784-11e5-801f-6657fa4cca2c.png)

These fbx files work perfectly is used in the UMA 1 Material Builder. They also work when converted for use in UMA 2. Error occurs if they are directly converted using UMA 2 slot builder.

This has been tested with 3ds MAX 2012 & 2016 with all FBX exporters 2012 - 2016 in both ASCII and binary format.

I can only assume that the fact there are now 2 scales shown on file import in unity 5 may have something to do with it. (import now has "scale factor" and non-editable "file scale")

Example files and testing available on request from:  secretanorak@outlook.com

**Comment by ecurtz** [comment]
Line 79 of UMASlotProcessingUtil.cs is messing up the new slot for SecretAnorak's example .FBX when it tries to remove unused bones from the skeleton:

resultingSkinnedMesh.bones = BuildNewReducedBonesList(resultingSkinnedMesh.bones, usedBonesDictionary);

**Comment by ecurtz** [comment]
Looks like maybe it is rebuilding the bones, but not the mesh? If bone count is the same it doesn't rebuild the mesh but it will still rebuild the bone list... ???

**Comment by Joen-UnLogick** [comment]
Strange since I've been working on an import pipeline and experienced no problems with this.

Definitely some sort of assumption about the structure of the fbx files because I know the uma fbxs still imports.

**Comment by ecurtz** [comment]
SecretAnorak tested the fix in commit 159412a25d318f092e0cc135d085bcffd6b5cc84 and confirms it fixed his file, so I'm gonna close this.
