### ISSUE TITLE
TextureMerge prefab sensitive to parent UMAGenerator transform

### ISSUE THREAD

**Issue by ecurtz** [huika/UMA#45]
As described in the forum thread here, rotating the UMAGenerator breaks atlas generation. We should probably ditch that prefab and have it build the camera in code, or at least put some sort of identity transform onto it before it's updated.

http://forum.unity3d.com/threads/uma-unity-multipurpose-avatar-on-the-asset-store.219175/page-65#post-2262366

**Comment by virror** [comment]
This is apparently fixed in an earlier commit.
