### ISSUE TITLE
PackRecipeV2 leaves out last slot

### ISSUE THREAD

**Issue by minh-gh** [huika/UMA#47]
Using the Menu Item "Save Selected Avatar(s) asset" saves an asset, but the Text Recipe is missing the last slot from the umaRecipe.slotDataList.
Must be because 

`int slotCount = umaRecipe.slotDataList.Length - umaRecipe.additionalSlotCount;`

in PackRecipeV2 method of UMAPackedRecipebase.cs

If there is an additional slot, which is not the last slot in the slotDataList, instead of the additional slot being skipped when saving, another slot at the last index will get skipped.

**Comment by Joen-UnLogick** [comment]
It was meant as a feature but the more we learn about how people use additional recipes the more it becomes clear it's not a feature. :)

The idea was that Slots with Colliders, Locomotion, etc should be added through additional recipes and shouldn't be serialized. However it's clear that those slots should instead carry a flag that they're not to be serialized.

**Comment by Joen-UnLogick** [comment]
Fixed in branch unity53
