### ISSUE TITLE
Character Created Event

### ISSUE THREAD

**Issue by minh-gh** [huika/UMA#48]
I'm calling a function with the help of the CharacterCreated Event, which I set up in the UMADynamicAvatar script in the Inspector Window (set to Runtime Only). 

My function switches the slots of my character by using UMADynamicAvatar.umaData.umaRecipe.SetSlot(int index, SlotData slot) and UMADynamicAvatar.umaData.GetSlot(index).AddOverlay(string name). 

However, calling my function via the CharacterCreated Event, the slots and overlays get added to the UMAData (I checked in the Inspector) but are not visible. If I delay my function call for just 1ms (via Invoke("myFunction", 0.001)), everything works fine.

**Comment by Joen-UnLogick** [comment]
The event is fired after the character is built... clearly too late to add new stuff...
