### ISSUE TITLE
Removing a slot from Generated asset causes the asset in scene to disappear (resolved)

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#49]
In the UMA wanderer refit, the character generates fine with all of the original slots in it, but once a slot is removed ie. wanderer scarf, or pants, the Avatar dissappears.

It happens during run time and also not during run time.

![screenhunter_337 sep 05 09 56](https://cloud.githubusercontent.com/assets/12765338/9699552/eea0b184-53b4-11e5-969c-b2f82833c69b.jpg)

**Comment by justbtoo** [comment]
Error message:

![screenhunter_339 sep 05 10 02](https://cloud.githubusercontent.com/assets/12765338/9699556/3fba1d4e-53b5-11e5-95e8-2a2e6ddf67e3.jpg)

**Comment by justbtoo** [comment]
Seems to be an issue with a slot. Looking at it now.

**Comment by justbtoo** [comment]
Was the import setting on one of the slots.

**Comment by Jaimi** [comment]
Closing issue
