### ISSUE TITLE
Character generates backwards

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#51]
In Scene Character creator. Unity 5.0

UMA Crowd settings: Generate UMA checked

![screenhunter_713 sep 20 11 38](https://cloud.githubusercontent.com/assets/12765338/9981484/7255804e-5f8c-11e5-8857-101e14b73938.jpg)

**Comment by Joen-UnLogick** [comment]
There is a reason scene 5 - character creator isn't on the asset store. The scene was never completed. 

This scene is not officially supported.

**Comment by justbtoo** [comment]
Hey Joen.

This is from the asset store PBR version. you can see it in the previews.

W

![screenhunter_716 sep 20 16 21](https://cloud.githubusercontent.com/assets/12765338/9982743/ceb3964c-5fb3-11e5-89de-9ba4bebef193.jpg)
