### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by adelphia** [huika/UMA#52]
Hi. I'm new to UMA so I viewed the documentation (UMA_Manual.pdf) but it is so outdated; it relates to version UMA version 1.0.1.0R. Will there be an update any time soon as the UMA_Manual.pdf is deprecated as it stands.

**Comment by nkv123** [comment]
I agree.

**Comment by SecretAnorak** [comment]
Unfortunately being a community project, contributors focus on refining and improving the system and no-one wants to spend time on documentation. I did try to address this with a video tutorial series which you can find here: https://www.youtube.com/watch?v=XN0E1G2ylbs&list=PLkDHFObfS19wRJ9vvaDTwCe-zRPv9jI25

**Comment by Joen-UnLogick** [comment]
duplicate of #9
