### ISSUE TITLE
New recipe UI issues

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#53]
New recipe UI with shared colors options bugs:

You need to add 4 in order for the metallic to show ;however, it is effected by texture 2 multiplier. I'm guessing that Albedo Color is 0, then texture 1 normal, and texture 2 metallic. Texture 3 effects nothing but is needed for the metallic.

Adjusting texture 1 color (normals) and then putting back to it's original color causes the normals to stay modified.

Unity 5.1

**Comment by Jaimi** [comment]
I did the shared colors editor - but it didn't introduce the idea of the channels, or what they affect, just the ability to edit colors. Is it behaving differently than the colors editor under the overlay? Can you create a small sample so I can see what you are seeing?

**Comment by justbtoo** [comment]
Hey Jaimi.

Heading off for the day.

Working from the top overlay (0 and 1) the color changes fine. The issue I think is the normals not going back to their original state after change the color back and the texture numbers. Texture 3 effects nothing but is need to use the metallic texture.

Will be back on tomorrow and check in then.

Regards

Will

--------------------------------------------
On Sun, 10/25/15, Jaimi <notifications@github.com> wrote:

 Subject: Re: [UMA] New recipe UI issues (#53)
 To: "huika/UMA" <UMA@noreply.github.com>
 Cc: "justbtoo" <williambarry02@yahoo.com>
 Date: Sunday, October 25, 2015, 4:59 PM
 
 I did the shared colors editor -
 but it didn't introduce the idea of the channels, or
 what they affect, just the ability to edit colors. Is it
 behaving differently than the colors editor under the
 overlay? Can you create a small sample so I can see what you
 are seeing? 
 
 —
 Reply to this email directly or view
 it on GitHub.
