### ISSUE TITLE
Unity 5.3 Removes Textures from Overlays

### ISSUE THREAD

**Issue by justbtoo** [huika/UMA#56]
I and one other person are having an issue with Unity 5.3 and UMA 2.0.5. Textures are getting removed from overlays. It seems some of the overlays will have them and some won't.

5.1.2 doesn't have the issue. Attached images of the missing textures and console errors. 

On my comp visual studio had an install issue. Don't know if that might be the cause. Will have to ask the other person.

![screenhunter_1872 dec 14 17 55](https://cloud.githubusercontent.com/assets/12765338/11796888/18da39d0-a28d-11e5-85ab-0599ae6bd455.png)
![screenhunter_1873 dec 14 17 55](https://cloud.githubusercontent.com/assets/12765338/11796889/18dd1b64-a28d-11e5-859e-1accabb3e869.png)

**Comment by Jaimi** [comment]
Are you still seeing this? I'm not able to duplicate it with 5.3.1.

**Comment by justbtoo** [comment]
Yep. Still getting it. Just tested. It does it with the UMA Face pack.

**Comment by SecretAnorak** [comment]
Have not come across this in 5.3.2

**Comment by Jaimi** [comment]
I believe this is happening because the PBR materials are not imported into the project. Perhaps we can just merge the materials with the main package.

**Comment by Jaimi** [comment]
I added informative errors and cleaned up the obj ref console spam.  Should we close this one out, or wait pending a decision on whether to move the PBR materials into the main package? 

What are your thoughts?

**Comment by justbtoo** [comment]
Nice. Thanks Jaimi. I thought that might have been the issue but wasn't sure. I would agree about adding them to the main pack.

**Comment by Jaimi** [comment]
This will be addressed in the next release - PBR will be included by default.
