### ISSUE TITLE
Warnings in VS 2015 with Unity 5.3.1f1

### ISSUE THREAD

**Issue by ChrisLangsenkamp** [huika/UMA#57]
![uma2 warnings](https://cloud.githubusercontent.com/assets/9826063/12125800/5a51d672-b3bb-11e5-81ad-bb8d1a7d651a.jpg)

**Comment by Jaimi** [comment]
When I get time I'll fix these warnings so they don't junk up the console. In the meantime, they are harmless and you can safely ignore them.

**Comment by Jaimi** [comment]
I've removed the LookLikeControls() calls, and disabled the warnings for the Slot (accessing the slotname and material). Closing.
