### ISSUE TITLE
ubuntu 14.04 ~ unity 5.3.0f4 ~ gone to UMA1 from UMA2

### ISSUE THREAD

**Issue by nkv123** [huika/UMA#58]
Today I tried UMA for the 1. time 3h ago, I know that linux unity3d (free) is experimental just do not have money for windows, since there is no money for windows mac should not be even considered.

1. a question. 
why are all avatars in UMA1 and UM2 shoeless

2. reasons for going back to UMA1:
 * out of 20 generated avatars in UMA2 around 12 or more are completely black (missing skins or something else)
 * out of 20 generated avatars in UMA2 around 5 do not have any wear upper and lower at all, excluding 5 at least 3 are missing upper or lower wear (Not for people who are not making sexy strip show games).
 * made nice change with setting gui compared to UMA1, but there are mixed labels breast, upper arm size, cant figure it out but its torso and arms regions.
 * Old documentation describes better UMA1 than UMA2

**Comment by Jaimi** [comment]
Tested working on Windows/Mac.
