### ISSUE TITLE
ExpressionPlayer Issue

### ISSUE THREAD

**Issue by Danyablett** [huika/UMA#60]
Whenever i have the expressionplayer on my uma, it resets all the umas face deformation. It does not actually reset the dna though, just the shape. For example, if i adjust the head size dna slider, nothing happens.

**Comment by yiuwa** [comment]
Hack: UMASkeleton.cs > SetPosition() > add db.umaTransform.position = position;

What's happening:
UMAExpressionPlayer.cs: In the Update(), expressionSet.ResetBones(umaData.skeleton) is continuely being called, which copies "umaData.skeleton.umaTransform" to "umaData.skeleton.boneTransform".
In customization scene, when slider updates, it calls UpdateUMABody() from UMAGeneratorBuiltin which eventually calls into UMASkeleton.cs. However, only the "boneTransform" is updated to the slider value, "umaTransform" remains default.
Expression player is continuously copy the default "umaTransform" value to the updated "boneTransform" which makes it unchangable.

note:
Similar hacks can add to scale and rotation as well. However, adding it to SetPositionRelative() makes it buggy. Someone please clarify the usage of bone transform, umaTransform.

**Comment by ecurtz** [comment]
Most of the bones used by the expression player aren't used by the DNA so there aren't many conflicts, but the head is one. What is supposed to be happening is that the head gets reset to the POST DNA default before the expression is applied, but it's getting reset to the PRE DNA default. This was tested and working at some point, but I think there were changes to some of the skeleton code causing this bug.

**Comment by ecurtz** [comment]
Fixed in 2cd19c5c24cf2f1c32e9e11584d9f3c8d9b9b9ec
