### ISSUE TITLE
Extract T-Pose not working

### ISSUE THREAD

**Issue by SecretAnorak** [huika/UMA#63]
With the current Git version (11th April 2016) I can no longer extract a T-pose.

ArgumentException: An empty file name is not valid.
System.IO.FileSystemInfo.CheckPath (System.String path) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileSystemInfo.cs:255)
System.IO.FileInfo..ctor (System.String fileName) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileInfo.cs:58)
(wrapper remoting-invoke-with-check) System.IO.FileInfo:.ctor (string)
UMAEditor.TPoseExtracter.ExtractTPose () (at Assets/Standard Assets/Editor/UMA/Core/TPoseExtracter.cs:23)

**Comment by SecretAnorak** [comment]
Checked With Repo version from (3rd March 2016) and T-pose extraction works.

**Comment by Jaimi** [comment]
Thanks, I'll take a look at it this evening.

**Comment by Jaimi** [comment]
This didn't happen to me, I'm guessing it's a platform specific bug.  
It appeared that Unity was passing an asset with a null value for the AssetPath. Someone had previously checked for this, but the latest change didn't account for that. Fixed.
