### ISSUE TITLE
avatar animation state preservation

### ISSUE THREAD

**Issue by arcanor** [huika/UMA#7]
I'm instantiating a character avatar, and immediately upon creation I'm calling animator.enabled=false;  

the animator component re-enables itself 3 frames later, due to UMA internals

can the animator.enabled state be preserved, even when re-creating the avatar?

I've worked around the problem for now, by checking the state every Update(), and fixing it if it's out of sync, however this should probably be taken care of in UMA so it doesn't happen in the first place.

Thanks! :)

**Comment by Joen-UnLogick** [comment]
There is a slight animation slowdown when rebuilding, if you do it many frames in a row you'll notice it. But it's as good as can be with the current mecanim.
