### ISSUE TITLE
problem unity Unity 5.5.0f3 (64-bit) UmaTPose.cs

### ISSUE THREAD

**Issue by darkrurik** [huika/UMA#70]
UmaTPose.cs

transformModified error obsolete

**Comment by bibleuspro** [comment]
I can confirm this too.
_Assets/Standard Assets/UMA/Core/Scripts/UmaTPose.cs(113,14): error CS0619: `UnityEngine.SkeletonBone.transformModified' is obsolete: `transformModified is no longer used and has been deprecated.'_

Also on lines:
178
247

**Comment by Jaimi** [comment]
This is fixed in the Unity53 branch.
