### ISSUE TITLE
Dynamic Character System errors on Unity 5.5.0p3

### ISSUE THREAD

**Issue by agentc0re** [huika/UMA#73]
Screen shot of the errors
https://gyazo.com/dfd6f36abc4f09e819cb154832098cfd

These are preventing me from compiling.

**Comment by learnix-xx** [comment]
Okay i thought maybe I installed the wrong things.  Grabbed the latest UMA 2.1 from the unity53 branch.  Installed it.  Play function works the first time.  When i try to build i now get these two errors: 
https://gyazo.com/641ed59d109d9bdf3a41eace304e77b6

After that, I can no longer play the scene either.  Both say that their are script errors that I need to fix.

**Comment by agentc0re** [comment]
Okay so i change the code from the above error to this
`#if UNITY_EDITOR
                    AssetDatabase.CreateAsset(asset, filePath);
					AssetDatabase.SaveAssets();
#endif`

Now I get some more errors. I'm not sure if doing the above is the right thing to do though.  It did remove the error however.

New errors:
https://gyazo.com/8cd2807b5c66678410d8373d48f0922d

**Comment by agentc0re** [comment]
When i debugged the last errors i gave you I looked at the file, UMABonePose.cs
At line 89 i changed the code to the following.  Doing so removed my errors as well.
`//#if UNITY_EDITOR
		/// <summary>
		/// Adds a transform into the pose. Editor only.
		/// </summary>
		/// <param name="bone">Transform.</param>
		/// <param name="position">Position.</param>
		/// <param name="rotation">Rotation.</param>
		/// <param name="scale">Scale.</param>
		public void AddBone(Transform bone, Vector3 position, Quaternion rotation, Vector3 scale)
		{
			PoseBone pose = new PoseBone();
			pose.bone = bone.name;
			pose.hash = UMAUtils.StringToHash(bone.name);
			pose.position = position - bone.localPosition;
			pose.rotation = Quaternion.Inverse(bone.localRotation) * rotation;
			pose.scale = new Vector3(scale.x / bone.localScale.x,
									scale.y / bone.localScale.y,
									scale.z / bone.localScale.z);
#if UNITY_EDITOR
            ArrayUtility.Add(ref poses, pose);
#endif
        }
//#endif`

**Comment by agentc0re** [comment]
> //#if UNITY_EDITOR
		/// <summary>
		/// Adds a transform into the pose. Editor only.
		/// </summary>
		/// <param name="bone">Transform.</param>
		/// <param name="position">Position.</param>
		/// <param name="rotation">Rotation.</param>
		/// <param name="scale">Scale.</param>
		public void AddBone(Transform bone, Vector3 position, Quaternion rotation, Vector3 scale)
		{
			PoseBone pose = new PoseBone();
			pose.bone = bone.name;
			pose.hash = UMAUtils.StringToHash(bone.name);
			pose.position = position - bone.localPosition;
			pose.rotation = Quaternion.Inverse(bone.localRotation) * rotation;
			pose.scale = new Vector3(scale.x / bone.localScale.x,
									scale.y / bone.localScale.y,
									scale.z / bone.localScale.z);
#if UNITY_EDITOR
            ArrayUtility.Add(ref poses, pose);
#endif
        }
//#endif

**Comment by agentc0re** [comment]
uhhhg.  Okay while doing what I did made the program buildable, i still got the same error in the console.
So for now i've commented out all the #if UNITY_EDITOR and #endif statements.

I will report back on what happens after that.

**Comment by Jaimi** [comment]
Please pull the latest code. I've fixed the issue in the save function, and was able to successfully build an executable.
