### ISSUE TITLE
Cant access the website/wiki for UMA

### ISSUE THREAD

**Issue by agentc0re** [huika/UMA#74]
when attempting to access:  https://uma.unity3d.com/wiki/
I get the following error:

> Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation:
XID: 69781198
Varnish cache server

Is it possible to just start the wiki on github?

Side request: Can you change the default repo to unity53? I'm sure its the only reason any of us are coming here.  :D  If not, thats cool too.

**Comment by Jaimi** [comment]
New wiki is: 

http://umawiki.secretanorak.com/Main_Page

We're working to get this ready for release. Hopefully very soon.
